apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ismy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0034-tenant/tkrw-pr712-0075-0034-app/devfile-sample-ismy@sha256:55edbb0a6039b6bf2a5be263c2717e46e6b06f88c076fc66d46b0190fd10c273
        name: my-nodejs
        resources: {}
status: {}
